//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scriptes/Core/Input/GameplayUIActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameplayUIActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameplayUIActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameplayUIActions"",
    ""maps"": [
        {
            ""name"": ""GameplayUIMap"",
            ""id"": ""83711f42-400a-4e63-94d9-2a16ffd67b39"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c60ae9db-c45c-458c-9c74-7f5e28f634b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1dcf4a35-fea1-47e9-87c8-7d440606e155"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayUIMap
        m_GameplayUIMap = asset.FindActionMap("GameplayUIMap", throwIfNotFound: true);
        m_GameplayUIMap_Pause = m_GameplayUIMap.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayUIMap
    private readonly InputActionMap m_GameplayUIMap;
    private IGameplayUIMapActions m_GameplayUIMapActionsCallbackInterface;
    private readonly InputAction m_GameplayUIMap_Pause;
    public struct GameplayUIMapActions
    {
        private @GameplayUIActions m_Wrapper;
        public GameplayUIMapActions(@GameplayUIActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_GameplayUIMap_Pause;
        public InputActionMap Get() { return m_Wrapper.m_GameplayUIMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayUIMapActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayUIMapActions instance)
        {
            if (m_Wrapper.m_GameplayUIMapActionsCallbackInterface != null)
            {
                @Pause.started -= m_Wrapper.m_GameplayUIMapActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_GameplayUIMapActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_GameplayUIMapActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_GameplayUIMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public GameplayUIMapActions @GameplayUIMap => new GameplayUIMapActions(this);
    public interface IGameplayUIMapActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
